[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.3.19
    bblanchon/ArduinoJson @ ^6.21.3
    tzapu/WiFiManager @ ^2.0.16-rc.2
    mandulaj/PZEM-004T-v30 @ ^1.1.2
    mathertel/RotaryEncoder @ ^1.5.3

build_flags = 
    -D CORE_DEBUG_LEVEL=5
